---
- name: Deploy MCA application on EKS
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - name: Configure kubeconfig for EKS
      ansible.builtin.command:
        aws eks update-kubeconfig --region {{ aws_region }} --name {{ eks_cluster_name }}

    - name: Check EKS connection
      ansible.builtin.command:
        kubectl get nodes

  roles:
    - namesapce
    - database
    - backend
    - frontend
    - ingress

